name: tusc
description: A tus client for dart to allow resumable uploads using the tus protocol (https://tus.io/).
version: 2.1.0
homepage: https://github.com/luis901101/tusc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  cross_file: ^0.3.4+2
  hive_ce: ^2.11.3
  path: ^1.9.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
